config/routes.rb
Rails.application.routes.draw do
  root "top#index"

  resources :incomes
  resources :fixedcosts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixedcost.rb
class Fixedcost < ApplicationRecord
end

app/models/income.rb
class Income < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fixedcosts_controller.rb
class FixedcostsController < ApplicationController
  def index
    @fixedcosts = Fixedcost.order(created_at: :asc)
  end
  def show
  end
  def new
    @fixedcost = Fixedcost.new()
  end
  def edit
  end
  def create
    @fixedcost = Fixedcost.new(params[:fixedcost])
		if @fixedcost.save
			redirect_to @fixedcost, notice: "固定費科目を登録しました"
		else
			render "new"

  end
  def update
    @fixedcost.assign_attributes(params[:fixedcost])
		if @fixedcost.save
			redirect_to @fixedcost, notice: "固定費科目を登録しました"
		else
      render "new"
    end

  end 
  def destroy
    @fixedcost = Fixedcost.find(params[:id])
		@fixedcost.destroy
		redirect_to :fixedcosts, notice: "科目を削除しました。"
  end

  private
  def set_income
    @fixedcost = Fixedcost.find(params[:id])
  end

  def fixedcost_params
    params.require(:income).permit(:name, :description)
  end


end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

  def index
    @incomes = Income.order(created_at: :asc)
  end

  def show
  end
  
  def new
    @income = Income.new()
  end

  def edit
  end

  def create
    @income = Income.new(income_params)
    if @income.save
      redirect_to @income, notice: "収入科目を登録しました"
    else 
      render "new"
    end
  end

  def update
    @income.assign_attributes(params[:income])
    if @income.save
      redirect_to @income, notice: "収入科目を登録しました"
    else 
      render "new"
    end
  end

  def destroy
    @income.destroy
    redirect_to :incomes, notice: "科目を削除しました"
  end

private
  def set_income
    @income = Income.find(params[:id])
  end

  def income_params
    params.require(:income).permit(:name, :description)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fixedcosts_helper.rb
module FixedcostsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/fixedcosts/_form.html.haml
= link_to "固定費科目一覧に戻る",  fixedcosts_path
.content
  .content__box
    .content__box__label= form.label :name, "名称"
    .content__box__text= form.text_field :name
  .content__box
    .content__box__label= form.label :description, "説明"
    .content__box__text= form.text_field :description

app/views/fixedcosts/edit.html.haml
%h1.title
  固定費科目編集
= form_for @fixedcost do |form|
  = render "form", form: form
  = form.submit
  

app/views/fixedcosts/index.html.haml
%h2.title
  収入科目一覧
.link1
  = link_to "固定費科目の新規登録", new_fixedcost_path
-if @fixedcosts.present?
  .content
    .content__head
      %p
        科目名
      %p
        備考
      %p
        操作
    .content__body
      -@fixedcosts.each do |fixedcost|
        .content__body__name= fixedcost.name
        .content__body__description= fixedcost.description
        .content__body__link2
          =link_to "編集", edit_fixedcost_path
        .content__body__link2
          =link_to "削除", fixcost, method: :delete, data: {confirm: "本当に削除しますか？"}
-else
  %p2 登録されている固定費科目がありません。

app/views/fixedcosts/new.html.haml
%h1.title
  固定費科目登録
= form_for @fixedcost do |form|
  = render "form", form: form
  = form.submit
  

app/views/fixedcosts/show.html.haml
%h2.text 固定費科目の詳細
= link_to "編集", edit_fixedcost_path
= link_to "固定費科目一覧へ戻る", fixedcosts_path
-# = succeed "\u{3000}" do
-#   .content
-#     .content__box
-#       .content__box__text 名称
-#       .content__box__puts
-#         =@income.name
-#       .content__box__text 説明
-#       .content__box__puts
-#         =@income.description

app/views/incomes/_form.html.haml
= link_to "収入科目一覧に戻る",  incomes_path
.content
  .content__box
    .content__box__label= form.label :name, "名称"
    .content__box__text= form.text_field :name
  .content__box
    .content__box__label= form.label :description, "説明"
    .content__box__text= form.text_field :description

app/views/incomes/edit.html.haml
%h1.title
  収入科目編集
= form_for @income do |form|
  = render "form", form: form
  = form.submit
  

app/views/incomes/index.html.haml
%h2.title
  収入科目一覧
.link1
  = link_to "収入科目の新規登録", new_income_path
-if @incomes.present?
  .content
    .content__head
      %p
        科目名
      %p
        備考
      %p
        操作
    .content__body
      -@incomes.each do |income|
        .content__body__name= income.name
        .content__body__description= income.description
        .content__body__link2
          =link_to "編集", edit_income_path
        .content__body__link2
          =link_to "削除", income, method: :delete, data: {confirm: "本当に削除しますか？"}
-else
  %p2 登録されている収入科目がありません。

app/views/incomes/new.html.haml
%h1.title
  収入科目登録
= form_for @income do |form|
  = render "form", form: form
  = form.submit
  

app/views/incomes/show.html.haml
%h2.text 収入科目の詳細
= link_to "編集", [:edit, @income]
= link_to "収入科目一覧へ戻る", incomes_path
= succeed "\u{3000}" do
  .content
    .content__box
      .content__box__text 名称
      .content__box__puts= @income.name
    %tr
      .content__box__text 説明
      .content__box__puts= @income.description

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Kakeibo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -if flash.notice
      = flash.notice 
    = yield

app/views/top/index.html.haml
%h1.header
  家計簿アプリ

.body
  %h2.body__text1
    科目設定
    %ul 
      %li=link_to "収入科目設定", incomes_path
      %li=link_to "固定費科目設定", fixedcosts_path